### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by bringen** [facebookexperimental/eden#4]
This looks cool 👍 What is the status of the project? is it actively being worked on?

**Comment by wez** [comment]
It's actively being worked on inside FB, but it's not ready to be used outside just yet, largely because there's no supported way to build it externally at the moment, but also because we're not quite ready for non-expert users to try to run it.

It's present here on Github because Buck and Watchman need some adjustments to operate correctly when used with eden, and that is easier for non-FB folks to understand and follow if the code is visible here, even though they can't run it yet.
