### ISSUE TITLE
Basic Install and setup documentation

### ISSUE THREAD

**Issue by C00IHandLuke** [facebookexperimental/eden#7]
Would it be possible to add some basic Install and setup documentation.

The main readme build steps and the eden/docs are good.

If there was a basic or recommended install and setup doc that could help bridge the gap between the build and the config docs that would be very useful.

I am able to build the project and create the eden.zip file and use basic commands like `eden help` but when running
`$ eden start`
I get the error: 
`error: unable to find edenfs executable`

Any install and setup documentation or comments would be greatly appreciated.

Thank you

eden commit: c2944f20d807e2a8ff60ea9a06d1954abfd57126
OS: Ubuntu 18.04.2 LTS

**Comment by wez** [comment]
As alluded to in https://github.com/facebookexperimental/eden/issues/9#issuecomment-473355776, we're not quite ready to build and be useful outside of FB, and can't currently share a timeline for when we will be in that state.

**Comment by ahornby** [comment]
Current state:  The OSS build completes now for Eden CLI build and test, Mononoke build and test and Eden FS build. README.md is updated with build steps using getdeps.py to coordinate.  EdenFS tests hang about half way through when I run them on github actions, probably due to config missing that is present on our internal hosts.
