### ISSUE TITLE
Add Travis CI support

### ISSUE THREAD

**Issue by JoeLoser** [facebookexperimental/eden#9]
It would be nice to have Travis CI support like several other FB open source repos (Folly, Thrift, etc.). Are there any plans to add it?

**Comment by wez** [comment]
We've done some groundwork for making it possible to build with cmake, but at the moment things are made more complicated because there are some important pieces that currently live in a private github repo.  We're not ready to flip the bit to allow access to those pieces, so the build would either fail or not have all the pieces it needs.

We can't share a timeline for when this will happen, so unfortunately you'll need to sit tight for now!

**Comment by JoeLoser** [comment]
Thanks for the info @wez. Look forward to being able to play around with eden and contribute when it's ready for open source developers.

**Comment by Daniel15** [comment]
Why Travis rather than CircleCI or Azure DevOps? I think CircleCI has a lot more features than Travis does.

**Comment by tatarianaster** [comment]
try if i can comment

**Comment by quark-zju** [comment]
Closing as we do have a bunch of GitHub workflows now.
